package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

/*ListRepoTagsParams contains all the parameters to send to the API endpoint
for the list repo tags operation typically these are written to a http.Request
*/
type ListRepoTagsParams struct {

	/*Limit
	  Limit to the number of results to return per page. Max 100.

	*/
	Limit int64
	/*Page
	  Page index for the results. Default 1.

	*/
	Page int64
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*SpecificTag
	  Filters the tags to the specific tag.

	*/
	SpecificTag string
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoTagsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// query param limit
	if err := r.SetQueryParam("limit", swag.FormatInt64(o.Limit)); err != nil {
		return err
	}

	// query param page
	if err := r.SetQueryParam("page", swag.FormatInt64(o.Page)); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// query param specificTag
	if err := r.SetQueryParam("specificTag", o.SpecificTag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
