package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/coreos/go-quay/models"
)

// RevertTagReader is a Reader for the RevertTag structure.
type RevertTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *RevertTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewRevertTagCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewRevertTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewRevertTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewRevertTagForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewRevertTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRevertTagCreated creates a RevertTagCreated with default headers values
func NewRevertTagCreated() *RevertTagCreated {
	return &RevertTagCreated{}
}

/*RevertTagCreated handles this case with default header values.

Successful creation
*/
type RevertTagCreated struct {
}

func (o *RevertTagCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/tag/{tag}/revert][%d] revertTagCreated ", 201)
}

func (o *RevertTagCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevertTagBadRequest creates a RevertTagBadRequest with default headers values
func NewRevertTagBadRequest() *RevertTagBadRequest {
	return &RevertTagBadRequest{}
}

/*RevertTagBadRequest handles this case with default header values.

Bad Request
*/
type RevertTagBadRequest struct {
	Payload *models.APIError
}

func (o *RevertTagBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/tag/{tag}/revert][%d] revertTagBadRequest  %+v", 400, o.Payload)
}

func (o *RevertTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevertTagUnauthorized creates a RevertTagUnauthorized with default headers values
func NewRevertTagUnauthorized() *RevertTagUnauthorized {
	return &RevertTagUnauthorized{}
}

/*RevertTagUnauthorized handles this case with default header values.

Session required
*/
type RevertTagUnauthorized struct {
	Payload *models.APIError
}

func (o *RevertTagUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/tag/{tag}/revert][%d] revertTagUnauthorized  %+v", 401, o.Payload)
}

func (o *RevertTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevertTagForbidden creates a RevertTagForbidden with default headers values
func NewRevertTagForbidden() *RevertTagForbidden {
	return &RevertTagForbidden{}
}

/*RevertTagForbidden handles this case with default header values.

Unauthorized access
*/
type RevertTagForbidden struct {
	Payload *models.APIError
}

func (o *RevertTagForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/tag/{tag}/revert][%d] revertTagForbidden  %+v", 403, o.Payload)
}

func (o *RevertTagForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevertTagNotFound creates a RevertTagNotFound with default headers values
func NewRevertTagNotFound() *RevertTagNotFound {
	return &RevertTagNotFound{}
}

/*RevertTagNotFound handles this case with default header values.

Not found
*/
type RevertTagNotFound struct {
	Payload *models.APIError
}

func (o *RevertTagNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/tag/{tag}/revert][%d] revertTagNotFound  %+v", 404, o.Payload)
}

func (o *RevertTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
