package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// NewChangeOrganizationDetailsParams creates a new ChangeOrganizationDetailsParams object
// with the default values initialized.
func NewChangeOrganizationDetailsParams() *ChangeOrganizationDetailsParams {
	var ()
	return &ChangeOrganizationDetailsParams{}
}

/*ChangeOrganizationDetailsParams contains all the parameters to send to the API endpoint
for the change organization details operation typically these are written to a http.Request
*/
type ChangeOrganizationDetailsParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.UpdateOrg
	/*Orgname
	  The name of the organization

	*/
	Orgname string
}

// WithBody adds the body to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithBody(body *models.UpdateOrg) *ChangeOrganizationDetailsParams {
	o.Body = body
	return o
}

// WithOrgname adds the orgname to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithOrgname(orgname string) *ChangeOrganizationDetailsParams {
	o.Orgname = orgname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeOrganizationDetailsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.UpdateOrg)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
