package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationMemberParams creates a new GetOrganizationMemberParams object
// with the default values initialized.
func NewGetOrganizationMemberParams() *GetOrganizationMemberParams {
	var ()
	return &GetOrganizationMemberParams{}
}

/*GetOrganizationMemberParams contains all the parameters to send to the API endpoint
for the get organization member operation typically these are written to a http.Request
*/
type GetOrganizationMemberParams struct {

	/*Membername
	  The username of the organization member

	*/
	Membername string
	/*Orgname
	  The name of the organization

	*/
	Orgname string
}

// WithMembername adds the membername to the get organization member params
func (o *GetOrganizationMemberParams) WithMembername(Membername string) *GetOrganizationMemberParams {
	o.Membername = Membername
	return o
}

// WithOrgname adds the orgname to the get organization member params
func (o *GetOrganizationMemberParams) WithOrgname(Orgname string) *GetOrganizationMemberParams {
	o.Orgname = Orgname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param membername
	if err := r.SetPathParam("membername", o.Membername); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
