package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// GetOrganizationApplicationReader is a Reader for the GetOrganizationApplication structure.
type GetOrganizationApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetOrganizationApplicationReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOrganizationApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetOrganizationApplicationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetOrganizationApplicationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetOrganizationApplicationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetOrganizationApplicationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationApplicationOK creates a GetOrganizationApplicationOK with default headers values
func NewGetOrganizationApplicationOK() *GetOrganizationApplicationOK {
	return &GetOrganizationApplicationOK{}
}

/*GetOrganizationApplicationOK handles this case with default header values.

Successful invocation
*/
type GetOrganizationApplicationOK struct {
}

func (o *GetOrganizationApplicationOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/applications/{client_id}][%d] getOrganizationApplicationOK ", 200)
}

func (o *GetOrganizationApplicationOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationApplicationBadRequest creates a GetOrganizationApplicationBadRequest with default headers values
func NewGetOrganizationApplicationBadRequest() *GetOrganizationApplicationBadRequest {
	return &GetOrganizationApplicationBadRequest{}
}

/*GetOrganizationApplicationBadRequest handles this case with default header values.

Bad Request
*/
type GetOrganizationApplicationBadRequest struct {
	Payload *models.GeneralError
}

func (o *GetOrganizationApplicationBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/applications/{client_id}][%d] getOrganizationApplicationBadRequest  %+v", 400, o.Payload)
}

func (o *GetOrganizationApplicationBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationApplicationUnauthorized creates a GetOrganizationApplicationUnauthorized with default headers values
func NewGetOrganizationApplicationUnauthorized() *GetOrganizationApplicationUnauthorized {
	return &GetOrganizationApplicationUnauthorized{}
}

/*GetOrganizationApplicationUnauthorized handles this case with default header values.

Session required
*/
type GetOrganizationApplicationUnauthorized struct {
}

func (o *GetOrganizationApplicationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/applications/{client_id}][%d] getOrganizationApplicationUnauthorized ", 401)
}

func (o *GetOrganizationApplicationUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationApplicationForbidden creates a GetOrganizationApplicationForbidden with default headers values
func NewGetOrganizationApplicationForbidden() *GetOrganizationApplicationForbidden {
	return &GetOrganizationApplicationForbidden{}
}

/*GetOrganizationApplicationForbidden handles this case with default header values.

Unauthorized access
*/
type GetOrganizationApplicationForbidden struct {
}

func (o *GetOrganizationApplicationForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/applications/{client_id}][%d] getOrganizationApplicationForbidden ", 403)
}

func (o *GetOrganizationApplicationForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationApplicationNotFound creates a GetOrganizationApplicationNotFound with default headers values
func NewGetOrganizationApplicationNotFound() *GetOrganizationApplicationNotFound {
	return &GetOrganizationApplicationNotFound{}
}

/*GetOrganizationApplicationNotFound handles this case with default header values.

Not found
*/
type GetOrganizationApplicationNotFound struct {
}

func (o *GetOrganizationApplicationNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/applications/{client_id}][%d] getOrganizationApplicationNotFound ", 404)
}

func (o *GetOrganizationApplicationNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
