package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type GetOrganizationMemberReader struct {
	formats strfmt.Registry
}

func (o *GetOrganizationMemberReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetOrganizationMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetOrganizationMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetOrganizationMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetOrganizationMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetOrganizationMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationMemberOK creates a GetOrganizationMemberOK with default headers values
func NewGetOrganizationMemberOK() *GetOrganizationMemberOK {
	return &GetOrganizationMemberOK{}
}

/*GetOrganizationMemberOK

Successful invocation
*/
type GetOrganizationMemberOK struct {
}

func (o *GetOrganizationMemberOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/members/{membername}][%d] getOrganizationMemberOK ", 200)
}

func (o *GetOrganizationMemberOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationMemberBadRequest creates a GetOrganizationMemberBadRequest with default headers values
func NewGetOrganizationMemberBadRequest() *GetOrganizationMemberBadRequest {
	return &GetOrganizationMemberBadRequest{}
}

/*GetOrganizationMemberBadRequest

Bad Request
*/
type GetOrganizationMemberBadRequest struct {
	Payload *models.GeneralError
}

func (o *GetOrganizationMemberBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/members/{membername}][%d] getOrganizationMemberBadRequest  %+v", 400, o.Payload)
}

func (o *GetOrganizationMemberBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationMemberUnauthorized creates a GetOrganizationMemberUnauthorized with default headers values
func NewGetOrganizationMemberUnauthorized() *GetOrganizationMemberUnauthorized {
	return &GetOrganizationMemberUnauthorized{}
}

/*GetOrganizationMemberUnauthorized

Session required
*/
type GetOrganizationMemberUnauthorized struct {
}

func (o *GetOrganizationMemberUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/members/{membername}][%d] getOrganizationMemberUnauthorized ", 401)
}

func (o *GetOrganizationMemberUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationMemberForbidden creates a GetOrganizationMemberForbidden with default headers values
func NewGetOrganizationMemberForbidden() *GetOrganizationMemberForbidden {
	return &GetOrganizationMemberForbidden{}
}

/*GetOrganizationMemberForbidden

Unauthorized access
*/
type GetOrganizationMemberForbidden struct {
}

func (o *GetOrganizationMemberForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/members/{membername}][%d] getOrganizationMemberForbidden ", 403)
}

func (o *GetOrganizationMemberForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationMemberNotFound creates a GetOrganizationMemberNotFound with default headers values
func NewGetOrganizationMemberNotFound() *GetOrganizationMemberNotFound {
	return &GetOrganizationMemberNotFound{}
}

/*GetOrganizationMemberNotFound

Not found
*/
type GetOrganizationMemberNotFound struct {
}

func (o *GetOrganizationMemberNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/members/{membername}][%d] getOrganizationMemberNotFound ", 404)
}

func (o *GetOrganizationMemberNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
