package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// DeleteOrganizationTeamMemberReader is a Reader for the DeleteOrganizationTeamMember structure.
type DeleteOrganizationTeamMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteOrganizationTeamMemberReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteOrganizationTeamMemberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteOrganizationTeamMemberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteOrganizationTeamMemberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteOrganizationTeamMemberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteOrganizationTeamMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteOrganizationTeamMemberNoContent creates a DeleteOrganizationTeamMemberNoContent with default headers values
func NewDeleteOrganizationTeamMemberNoContent() *DeleteOrganizationTeamMemberNoContent {
	return &DeleteOrganizationTeamMemberNoContent{}
}

/*DeleteOrganizationTeamMemberNoContent handles this case with default header values.

Deleted
*/
type DeleteOrganizationTeamMemberNoContent struct {
}

func (o *DeleteOrganizationTeamMemberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/organization/{orgname}/team/{teamname}/members/{membername}][%d] deleteOrganizationTeamMemberNoContent ", 204)
}

func (o *DeleteOrganizationTeamMemberNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationTeamMemberBadRequest creates a DeleteOrganizationTeamMemberBadRequest with default headers values
func NewDeleteOrganizationTeamMemberBadRequest() *DeleteOrganizationTeamMemberBadRequest {
	return &DeleteOrganizationTeamMemberBadRequest{}
}

/*DeleteOrganizationTeamMemberBadRequest handles this case with default header values.

Bad Request
*/
type DeleteOrganizationTeamMemberBadRequest struct {
	Payload *models.GeneralError
}

func (o *DeleteOrganizationTeamMemberBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/organization/{orgname}/team/{teamname}/members/{membername}][%d] deleteOrganizationTeamMemberBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteOrganizationTeamMemberBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteOrganizationTeamMemberUnauthorized creates a DeleteOrganizationTeamMemberUnauthorized with default headers values
func NewDeleteOrganizationTeamMemberUnauthorized() *DeleteOrganizationTeamMemberUnauthorized {
	return &DeleteOrganizationTeamMemberUnauthorized{}
}

/*DeleteOrganizationTeamMemberUnauthorized handles this case with default header values.

Session required
*/
type DeleteOrganizationTeamMemberUnauthorized struct {
}

func (o *DeleteOrganizationTeamMemberUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/organization/{orgname}/team/{teamname}/members/{membername}][%d] deleteOrganizationTeamMemberUnauthorized ", 401)
}

func (o *DeleteOrganizationTeamMemberUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationTeamMemberForbidden creates a DeleteOrganizationTeamMemberForbidden with default headers values
func NewDeleteOrganizationTeamMemberForbidden() *DeleteOrganizationTeamMemberForbidden {
	return &DeleteOrganizationTeamMemberForbidden{}
}

/*DeleteOrganizationTeamMemberForbidden handles this case with default header values.

Unauthorized access
*/
type DeleteOrganizationTeamMemberForbidden struct {
}

func (o *DeleteOrganizationTeamMemberForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/organization/{orgname}/team/{teamname}/members/{membername}][%d] deleteOrganizationTeamMemberForbidden ", 403)
}

func (o *DeleteOrganizationTeamMemberForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationTeamMemberNotFound creates a DeleteOrganizationTeamMemberNotFound with default headers values
func NewDeleteOrganizationTeamMemberNotFound() *DeleteOrganizationTeamMemberNotFound {
	return &DeleteOrganizationTeamMemberNotFound{}
}

/*DeleteOrganizationTeamMemberNotFound handles this case with default header values.

Not found
*/
type DeleteOrganizationTeamMemberNotFound struct {
}

func (o *DeleteOrganizationTeamMemberNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/organization/{orgname}/team/{teamname}/members/{membername}][%d] deleteOrganizationTeamMemberNotFound ", 404)
}

func (o *DeleteOrganizationTeamMemberNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
