package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type DeleteTeamMemberEmailInviteReader struct {
	formats strfmt.Registry
}

func (o *DeleteTeamMemberEmailInviteReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		var result DeleteTeamMemberEmailInviteNoContent
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result DeleteTeamMemberEmailInviteBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("deleteTeamMemberEmailInviteBadRequest", &result, response.Code())

	case 401:
		var result DeleteTeamMemberEmailInviteUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("deleteTeamMemberEmailInviteUnauthorized", &result, response.Code())

	case 403:
		var result DeleteTeamMemberEmailInviteForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("deleteTeamMemberEmailInviteForbidden", &result, response.Code())

	case 404:
		var result DeleteTeamMemberEmailInviteNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("deleteTeamMemberEmailInviteNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

/*DeleteTeamMemberEmailInviteNoContent

Deleted
*/
type DeleteTeamMemberEmailInviteNoContent struct {
}

func (o *DeleteTeamMemberEmailInviteNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DeleteTeamMemberEmailInviteBadRequest

Bad Request
*/
type DeleteTeamMemberEmailInviteBadRequest struct {
	Payload *models.GeneralError
}

func (o *DeleteTeamMemberEmailInviteBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*DeleteTeamMemberEmailInviteUnauthorized

Session required
*/
type DeleteTeamMemberEmailInviteUnauthorized struct {
}

func (o *DeleteTeamMemberEmailInviteUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DeleteTeamMemberEmailInviteForbidden

Unauthorized access
*/
type DeleteTeamMemberEmailInviteForbidden struct {
}

func (o *DeleteTeamMemberEmailInviteForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*DeleteTeamMemberEmailInviteNotFound

Not found
*/
type DeleteTeamMemberEmailInviteNotFound struct {
}

func (o *DeleteTeamMemberEmailInviteNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
