package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteOrganizationTeamMemberParams creates a new DeleteOrganizationTeamMemberParams object
// with the default values initialized.
func NewDeleteOrganizationTeamMemberParams() *DeleteOrganizationTeamMemberParams {
	var ()
	return &DeleteOrganizationTeamMemberParams{}
}

/*DeleteOrganizationTeamMemberParams contains all the parameters to send to the API endpoint
for the delete organization team member operation typically these are written to a http.Request
*/
type DeleteOrganizationTeamMemberParams struct {

	/*Membername
	  The username of the team member

	*/
	Membername string
	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*Teamname
	  The name of the team

	*/
	Teamname string
}

// WithMembername adds the membername to the delete organization team member params
func (o *DeleteOrganizationTeamMemberParams) WithMembername(membername string) *DeleteOrganizationTeamMemberParams {
	o.Membername = membername
	return o
}

// WithOrgname adds the orgname to the delete organization team member params
func (o *DeleteOrganizationTeamMemberParams) WithOrgname(orgname string) *DeleteOrganizationTeamMemberParams {
	o.Orgname = orgname
	return o
}

// WithTeamname adds the teamname to the delete organization team member params
func (o *DeleteOrganizationTeamMemberParams) WithTeamname(teamname string) *DeleteOrganizationTeamMemberParams {
	o.Teamname = teamname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationTeamMemberParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param membername
	if err := r.SetPathParam("membername", o.Membername); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
