package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*InviteTeamMemberEmailParams contains all the parameters to send to the API endpoint
for the invite team member email operation typically these are written to a http.Request
*/
type InviteTeamMemberEmailParams struct {

	/*Email*/
	Email string
	/*Orgname*/
	Orgname string
	/*Teamname*/
	Teamname string
}

// WriteToRequest writes these params to a swagger request
func (o *InviteTeamMemberEmailParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
