package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type UpdateOrganizationTeamMemberReader struct {
	formats strfmt.Registry
}

func (o *UpdateOrganizationTeamMemberReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result UpdateOrganizationTeamMemberOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result UpdateOrganizationTeamMemberBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("updateOrganizationTeamMemberBadRequest", &result, response.Code())

	case 401:
		var result UpdateOrganizationTeamMemberUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("updateOrganizationTeamMemberUnauthorized", &result, response.Code())

	case 403:
		var result UpdateOrganizationTeamMemberForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("updateOrganizationTeamMemberForbidden", &result, response.Code())

	case 404:
		var result UpdateOrganizationTeamMemberNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("updateOrganizationTeamMemberNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

/*UpdateOrganizationTeamMemberOK

Successful invocation
*/
type UpdateOrganizationTeamMemberOK struct {
}

func (o *UpdateOrganizationTeamMemberOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UpdateOrganizationTeamMemberBadRequest

Bad Request
*/
type UpdateOrganizationTeamMemberBadRequest struct {
	Payload *models.GeneralError
}

func (o *UpdateOrganizationTeamMemberBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*UpdateOrganizationTeamMemberUnauthorized

Session required
*/
type UpdateOrganizationTeamMemberUnauthorized struct {
}

func (o *UpdateOrganizationTeamMemberUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UpdateOrganizationTeamMemberForbidden

Unauthorized access
*/
type UpdateOrganizationTeamMemberForbidden struct {
}

func (o *UpdateOrganizationTeamMemberForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UpdateOrganizationTeamMemberNotFound

Not found
*/
type UpdateOrganizationTeamMemberNotFound struct {
}

func (o *UpdateOrganizationTeamMemberNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
