package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewListTriggerRecentBuildsParams creates a new ListTriggerRecentBuildsParams object
// with the default values initialized.
func NewListTriggerRecentBuildsParams() *ListTriggerRecentBuildsParams {
	var ()
	return &ListTriggerRecentBuildsParams{}
}

/*ListTriggerRecentBuildsParams contains all the parameters to send to the API endpoint
for the list trigger recent builds operation typically these are written to a http.Request
*/
type ListTriggerRecentBuildsParams struct {

	/*Limit
	  The maximum number of builds to return

	*/
	Limit *int64
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*TriggerUUID
	  The UUID of the build trigger

	*/
	TriggerUUID string
}

// WithLimit adds the limit to the list trigger recent builds params
func (o *ListTriggerRecentBuildsParams) WithLimit(limit *int64) *ListTriggerRecentBuildsParams {
	o.Limit = limit
	return o
}

// WithRepository adds the repository to the list trigger recent builds params
func (o *ListTriggerRecentBuildsParams) WithRepository(repository string) *ListTriggerRecentBuildsParams {
	o.Repository = repository
	return o
}

// WithTriggerUUID adds the triggerUuid to the list trigger recent builds params
func (o *ListTriggerRecentBuildsParams) WithTriggerUUID(triggerUuid string) *ListTriggerRecentBuildsParams {
	o.TriggerUUID = triggerUuid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListTriggerRecentBuildsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param trigger_uuid
	if err := r.SetPathParam("trigger_uuid", o.TriggerUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
