package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/coreos/go-quay/models"
)

// NewChangeRepoVisibilityParams creates a new ChangeRepoVisibilityParams object
// with the default values initialized.
func NewChangeRepoVisibilityParams() *ChangeRepoVisibilityParams {
	var ()
	return &ChangeRepoVisibilityParams{}
}

/*ChangeRepoVisibilityParams contains all the parameters to send to the API endpoint
for the change repo visibility operation typically these are written to a http.Request
*/
type ChangeRepoVisibilityParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.ChangeVisibility
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
}

// WithBody adds the body to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithBody(Body *models.ChangeVisibility) *ChangeRepoVisibilityParams {
	o.Body = Body
	return o
}

// WithRepository adds the repository to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithRepository(Repository string) *ChangeRepoVisibilityParams {
	o.Repository = Repository
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeRepoVisibilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.ChangeVisibility)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
