package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type ChangeTeamPermissionsReader struct {
	formats strfmt.Registry
}

func (o *ChangeTeamPermissionsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewChangeTeamPermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewChangeTeamPermissionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewChangeTeamPermissionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewChangeTeamPermissionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewChangeTeamPermissionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeTeamPermissionsOK creates a ChangeTeamPermissionsOK with default headers values
func NewChangeTeamPermissionsOK() *ChangeTeamPermissionsOK {
	return &ChangeTeamPermissionsOK{}
}

/*ChangeTeamPermissionsOK

Successful invocation
*/
type ChangeTeamPermissionsOK struct {
}

func (o *ChangeTeamPermissionsOK) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repository/{repository}/permissions/team/{teamname}][%d] changeTeamPermissionsOK ", 200)
}

func (o *ChangeTeamPermissionsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeTeamPermissionsBadRequest creates a ChangeTeamPermissionsBadRequest with default headers values
func NewChangeTeamPermissionsBadRequest() *ChangeTeamPermissionsBadRequest {
	return &ChangeTeamPermissionsBadRequest{}
}

/*ChangeTeamPermissionsBadRequest

Bad Request
*/
type ChangeTeamPermissionsBadRequest struct {
	Payload *models.GeneralError
}

func (o *ChangeTeamPermissionsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repository/{repository}/permissions/team/{teamname}][%d] changeTeamPermissionsBadRequest  %+v", 400, o.Payload)
}

func (o *ChangeTeamPermissionsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeTeamPermissionsUnauthorized creates a ChangeTeamPermissionsUnauthorized with default headers values
func NewChangeTeamPermissionsUnauthorized() *ChangeTeamPermissionsUnauthorized {
	return &ChangeTeamPermissionsUnauthorized{}
}

/*ChangeTeamPermissionsUnauthorized

Session required
*/
type ChangeTeamPermissionsUnauthorized struct {
}

func (o *ChangeTeamPermissionsUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repository/{repository}/permissions/team/{teamname}][%d] changeTeamPermissionsUnauthorized ", 401)
}

func (o *ChangeTeamPermissionsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeTeamPermissionsForbidden creates a ChangeTeamPermissionsForbidden with default headers values
func NewChangeTeamPermissionsForbidden() *ChangeTeamPermissionsForbidden {
	return &ChangeTeamPermissionsForbidden{}
}

/*ChangeTeamPermissionsForbidden

Unauthorized access
*/
type ChangeTeamPermissionsForbidden struct {
}

func (o *ChangeTeamPermissionsForbidden) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repository/{repository}/permissions/team/{teamname}][%d] changeTeamPermissionsForbidden ", 403)
}

func (o *ChangeTeamPermissionsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeTeamPermissionsNotFound creates a ChangeTeamPermissionsNotFound with default headers values
func NewChangeTeamPermissionsNotFound() *ChangeTeamPermissionsNotFound {
	return &ChangeTeamPermissionsNotFound{}
}

/*ChangeTeamPermissionsNotFound

Not found
*/
type ChangeTeamPermissionsNotFound struct {
}

func (o *ChangeTeamPermissionsNotFound) Error() string {
	return fmt.Sprintf("[PUT /api/v1/repository/{repository}/permissions/team/{teamname}][%d] changeTeamPermissionsNotFound ", 404)
}

func (o *ChangeTeamPermissionsNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
