package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/coreos/go-quay/models"
)

// NewChangeTeamPermissionsParams creates a new ChangeTeamPermissionsParams object
// with the default values initialized.
func NewChangeTeamPermissionsParams() *ChangeTeamPermissionsParams {
	var ()
	return &ChangeTeamPermissionsParams{}
}

/*ChangeTeamPermissionsParams contains all the parameters to send to the API endpoint
for the change team permissions operation typically these are written to a http.Request
*/
type ChangeTeamPermissionsParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.TeamPermission
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Teamname
	  The name of the team to which the permission applies

	*/
	Teamname string
}

// WithBody adds the body to the change team permissions params
func (o *ChangeTeamPermissionsParams) WithBody(Body *models.TeamPermission) *ChangeTeamPermissionsParams {
	o.Body = Body
	return o
}

// WithRepository adds the repository to the change team permissions params
func (o *ChangeTeamPermissionsParams) WithRepository(Repository string) *ChangeTeamPermissionsParams {
	o.Repository = Repository
	return o
}

// WithTeamname adds the teamname to the change team permissions params
func (o *ChangeTeamPermissionsParams) WithTeamname(Teamname string) *ChangeTeamPermissionsParams {
	o.Teamname = Teamname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeTeamPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.TeamPermission)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
