package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteUserPermissionsParams creates a new DeleteUserPermissionsParams object
// with the default values initialized.
func NewDeleteUserPermissionsParams() *DeleteUserPermissionsParams {
	var ()
	return &DeleteUserPermissionsParams{}
}

/*DeleteUserPermissionsParams contains all the parameters to send to the API endpoint
for the delete user permissions operation typically these are written to a http.Request
*/
type DeleteUserPermissionsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Username
	  The username of the user to which the permission applies

	*/
	Username string
}

// WithRepository adds the repository to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithRepository(repository string) *DeleteUserPermissionsParams {
	o.Repository = repository
	return o
}

// WithUsername adds the username to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithUsername(username string) *DeleteUserPermissionsParams {
	o.Username = username
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserPermissionsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
