package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type ListRepoUserPermissionsReader struct {
	formats strfmt.Registry
}

func (o *ListRepoUserPermissionsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result ListRepoUserPermissionsOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result ListRepoUserPermissionsBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("listRepoUserPermissionsBadRequest", &result, response.Code())

	case 401:
		var result ListRepoUserPermissionsUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("listRepoUserPermissionsUnauthorized", &result, response.Code())

	case 403:
		var result ListRepoUserPermissionsForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("listRepoUserPermissionsForbidden", &result, response.Code())

	case 404:
		var result ListRepoUserPermissionsNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("listRepoUserPermissionsNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

/*ListRepoUserPermissionsOK

Successful invocation
*/
type ListRepoUserPermissionsOK struct {
}

func (o *ListRepoUserPermissionsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ListRepoUserPermissionsBadRequest

Bad Request
*/
type ListRepoUserPermissionsBadRequest struct {
	Payload *models.GeneralError
}

func (o *ListRepoUserPermissionsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*ListRepoUserPermissionsUnauthorized

Session required
*/
type ListRepoUserPermissionsUnauthorized struct {
}

func (o *ListRepoUserPermissionsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ListRepoUserPermissionsForbidden

Unauthorized access
*/
type ListRepoUserPermissionsForbidden struct {
}

func (o *ListRepoUserPermissionsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ListRepoUserPermissionsNotFound

Not found
*/
type ListRepoUserPermissionsNotFound struct {
}

func (o *ListRepoUserPermissionsNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
