package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepoTeamPermissionsParams creates a new ListRepoTeamPermissionsParams object
// with the default values initialized.
func NewListRepoTeamPermissionsParams() *ListRepoTeamPermissionsParams {
	var ()
	return &ListRepoTeamPermissionsParams{}
}

/*ListRepoTeamPermissionsParams contains all the parameters to send to the API endpoint
for the list repo team permissions operation typically these are written to a http.Request
*/
type ListRepoTeamPermissionsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
}

// WithRepository adds the repository to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) WithRepository(Repository string) *ListRepoTeamPermissionsParams {
	o.Repository = Repository
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoTeamPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
