package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new billing API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for billing API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ListOrgInvoices List the invoices for the specified orgnaization.
*/
func (a *Client) ListOrgInvoices(params *ListOrgInvoicesParams, authInfo runtime.ClientAuthInfoWriter) (*ListOrgInvoicesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListOrgInvoicesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listOrgInvoices",
		Method:             "GET",
		PathPattern:        "/api/v1/organization/{orgname}/invoices",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListOrgInvoicesReader{formats: a.formats},
		AuthInfo:           authInfo,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListOrgInvoicesOK), nil
}

/*
ListPlans List the avaialble plans.
*/
func (a *Client) ListPlans(params *ListPlansParams) (*ListPlansOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPlansParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listPlans",
		Method:             "GET",
		PathPattern:        "/api/v1/plans/",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListPlansReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListPlansOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
