package secscan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type GetRepoTagVulnerabilitiesReader struct {
	formats strfmt.Registry
}

func (o *GetRepoTagVulnerabilitiesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result GetRepoTagVulnerabilitiesOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result GetRepoTagVulnerabilitiesBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getRepoTagVulnerabilitiesBadRequest", &result, response.Code())

	case 401:
		var result GetRepoTagVulnerabilitiesUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getRepoTagVulnerabilitiesUnauthorized", &result, response.Code())

	case 403:
		var result GetRepoTagVulnerabilitiesForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getRepoTagVulnerabilitiesForbidden", &result, response.Code())

	case 404:
		var result GetRepoTagVulnerabilitiesNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getRepoTagVulnerabilitiesNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", nil, 0)
	}
}

/*
Successful invocation
*/
type GetRepoTagVulnerabilitiesOK struct {
}

func (o *GetRepoTagVulnerabilitiesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Bad Request
*/
type GetRepoTagVulnerabilitiesBadRequest struct {
}

func (o *GetRepoTagVulnerabilitiesBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Session required
*/
type GetRepoTagVulnerabilitiesUnauthorized struct {
}

func (o *GetRepoTagVulnerabilitiesUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Unauthorized access
*/
type GetRepoTagVulnerabilitiesForbidden struct {
}

func (o *GetRepoTagVulnerabilitiesForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Not found
*/
type GetRepoTagVulnerabilitiesNotFound struct {
}

func (o *GetRepoTagVulnerabilitiesNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
