package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAggregateRepoLogsParams creates a new GetAggregateRepoLogsParams object
// with the default values initialized.
func NewGetAggregateRepoLogsParams() *GetAggregateRepoLogsParams {
	var ()
	return &GetAggregateRepoLogsParams{}
}

/*GetAggregateRepoLogsParams contains all the parameters to send to the API endpoint
for the get aggregate repo logs operation typically these are written to a http.Request
*/
type GetAggregateRepoLogsParams struct {

	/*Endtime
	  Latest time to which to get logs (%m/%d/%Y %Z)

	*/
	Endtime *string
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Starttime
	  Earliest time from which to get logs (%m/%d/%Y %Z)

	*/
	Starttime *string
}

// WithEndtime adds the endtime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithEndtime(Endtime *string) *GetAggregateRepoLogsParams {
	o.Endtime = Endtime
	return o
}

// WithRepository adds the repository to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithRepository(Repository string) *GetAggregateRepoLogsParams {
	o.Repository = Repository
	return o
}

// WithStarttime adds the starttime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithStarttime(Starttime *string) *GetAggregateRepoLogsParams {
	o.Starttime = Starttime
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAggregateRepoLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Endtime != nil {

		// query param endtime
		var qrEndtime string
		if o.Endtime != nil {
			qrEndtime = *o.Endtime
		}
		qEndtime := qrEndtime
		if qEndtime != "" {
			if err := r.SetQueryParam("endtime", qEndtime); err != nil {
				return err
			}
		}

	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if o.Starttime != nil {

		// query param starttime
		var qrStarttime string
		if o.Starttime != nil {
			qrStarttime = *o.Starttime
		}
		qStarttime := qrStarttime
		if qStarttime != "" {
			if err := r.SetQueryParam("starttime", qStarttime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
