package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAggregateUserLogsParams creates a new GetAggregateUserLogsParams object
// with the default values initialized.
func NewGetAggregateUserLogsParams() *GetAggregateUserLogsParams {
	var ()
	return &GetAggregateUserLogsParams{}
}

/*GetAggregateUserLogsParams contains all the parameters to send to the API endpoint
for the get aggregate user logs operation typically these are written to a http.Request
*/
type GetAggregateUserLogsParams struct {

	/*Endtime
	  Latest time to which to get logs. (%m/%d/%Y %Z)

	*/
	Endtime *string
	/*Performer
	  Username for which to filter logs.

	*/
	Performer *string
	/*Starttime
	  Earliest time from which to get logs. (%m/%d/%Y %Z)

	*/
	Starttime *string
}

// WithEndtime adds the endtime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithEndtime(Endtime *string) *GetAggregateUserLogsParams {
	o.Endtime = Endtime
	return o
}

// WithPerformer adds the performer to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithPerformer(Performer *string) *GetAggregateUserLogsParams {
	o.Performer = Performer
	return o
}

// WithStarttime adds the starttime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithStarttime(Starttime *string) *GetAggregateUserLogsParams {
	o.Starttime = Starttime
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAggregateUserLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Endtime != nil {

		// query param endtime
		var qrEndtime string
		if o.Endtime != nil {
			qrEndtime = *o.Endtime
		}
		qEndtime := qrEndtime
		if qEndtime != "" {
			if err := r.SetQueryParam("endtime", qEndtime); err != nil {
				return err
			}
		}

	}

	if o.Performer != nil {

		// query param performer
		var qrPerformer string
		if o.Performer != nil {
			qrPerformer = *o.Performer
		}
		qPerformer := qrPerformer
		if qPerformer != "" {
			if err := r.SetQueryParam("performer", qPerformer); err != nil {
				return err
			}
		}

	}

	if o.Starttime != nil {

		// query param starttime
		var qrStarttime string
		if o.Starttime != nil {
			qrStarttime = *o.Starttime
		}
		qStarttime := qrStarttime
		if qStarttime != "" {
			if err := r.SetQueryParam("starttime", qStarttime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
