package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// GetAggregateOrgLogsReader is a Reader for the GetAggregateOrgLogs structure.
type GetAggregateOrgLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAggregateOrgLogsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAggregateOrgLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAggregateOrgLogsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAggregateOrgLogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetAggregateOrgLogsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetAggregateOrgLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAggregateOrgLogsOK creates a GetAggregateOrgLogsOK with default headers values
func NewGetAggregateOrgLogsOK() *GetAggregateOrgLogsOK {
	return &GetAggregateOrgLogsOK{}
}

/*GetAggregateOrgLogsOK handles this case with default header values.

Successful invocation
*/
type GetAggregateOrgLogsOK struct {
}

func (o *GetAggregateOrgLogsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/aggregatelogs][%d] getAggregateOrgLogsOK ", 200)
}

func (o *GetAggregateOrgLogsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAggregateOrgLogsBadRequest creates a GetAggregateOrgLogsBadRequest with default headers values
func NewGetAggregateOrgLogsBadRequest() *GetAggregateOrgLogsBadRequest {
	return &GetAggregateOrgLogsBadRequest{}
}

/*GetAggregateOrgLogsBadRequest handles this case with default header values.

Bad Request
*/
type GetAggregateOrgLogsBadRequest struct {
	Payload *models.GeneralError
}

func (o *GetAggregateOrgLogsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/aggregatelogs][%d] getAggregateOrgLogsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAggregateOrgLogsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAggregateOrgLogsUnauthorized creates a GetAggregateOrgLogsUnauthorized with default headers values
func NewGetAggregateOrgLogsUnauthorized() *GetAggregateOrgLogsUnauthorized {
	return &GetAggregateOrgLogsUnauthorized{}
}

/*GetAggregateOrgLogsUnauthorized handles this case with default header values.

Session required
*/
type GetAggregateOrgLogsUnauthorized struct {
}

func (o *GetAggregateOrgLogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/aggregatelogs][%d] getAggregateOrgLogsUnauthorized ", 401)
}

func (o *GetAggregateOrgLogsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAggregateOrgLogsForbidden creates a GetAggregateOrgLogsForbidden with default headers values
func NewGetAggregateOrgLogsForbidden() *GetAggregateOrgLogsForbidden {
	return &GetAggregateOrgLogsForbidden{}
}

/*GetAggregateOrgLogsForbidden handles this case with default header values.

Unauthorized access
*/
type GetAggregateOrgLogsForbidden struct {
}

func (o *GetAggregateOrgLogsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/aggregatelogs][%d] getAggregateOrgLogsForbidden ", 403)
}

func (o *GetAggregateOrgLogsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAggregateOrgLogsNotFound creates a GetAggregateOrgLogsNotFound with default headers values
func NewGetAggregateOrgLogsNotFound() *GetAggregateOrgLogsNotFound {
	return &GetAggregateOrgLogsNotFound{}
}

/*GetAggregateOrgLogsNotFound handles this case with default header values.

Not found
*/
type GetAggregateOrgLogsNotFound struct {
}

func (o *GetAggregateOrgLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/aggregatelogs][%d] getAggregateOrgLogsNotFound ", 404)
}

func (o *GetAggregateOrgLogsNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
