package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type ChangeOrganizationDetailsReader struct {
	formats strfmt.Registry
}

func (o *ChangeOrganizationDetailsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result ChangeOrganizationDetailsOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result ChangeOrganizationDetailsBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("changeOrganizationDetailsBadRequest", &result, response.Code())

	case 401:
		var result ChangeOrganizationDetailsUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("changeOrganizationDetailsUnauthorized", &result, response.Code())

	case 403:
		var result ChangeOrganizationDetailsForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("changeOrganizationDetailsForbidden", &result, response.Code())

	case 404:
		var result ChangeOrganizationDetailsNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("changeOrganizationDetailsNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", nil, 0)
	}
}

/*
Successful invocation
*/
type ChangeOrganizationDetailsOK struct {
}

func (o *ChangeOrganizationDetailsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Bad Request
*/
type ChangeOrganizationDetailsBadRequest struct {
}

func (o *ChangeOrganizationDetailsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Session required
*/
type ChangeOrganizationDetailsUnauthorized struct {
}

func (o *ChangeOrganizationDetailsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Unauthorized access
*/
type ChangeOrganizationDetailsForbidden struct {
}

func (o *ChangeOrganizationDetailsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Not found
*/
type ChangeOrganizationDetailsNotFound struct {
}

func (o *ChangeOrganizationDetailsNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
