package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"
)

type RegenerateUserRobotTokenReader struct {
	formats strfmt.Registry
}

func (o *RegenerateUserRobotTokenReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result RegenerateUserRobotTokenOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result RegenerateUserRobotTokenBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("regenerateUserRobotTokenBadRequest", &result, response.Code())

	case 401:
		var result RegenerateUserRobotTokenUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("regenerateUserRobotTokenUnauthorized", &result, response.Code())

	case 403:
		var result RegenerateUserRobotTokenForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("regenerateUserRobotTokenForbidden", &result, response.Code())

	case 404:
		var result RegenerateUserRobotTokenNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("regenerateUserRobotTokenNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", nil, 0)
	}
}

/*
Successful invocation
*/
type RegenerateUserRobotTokenOK struct {
}

func (o *RegenerateUserRobotTokenOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Bad Request
*/
type RegenerateUserRobotTokenBadRequest struct {
}

func (o *RegenerateUserRobotTokenBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Session required
*/
type RegenerateUserRobotTokenUnauthorized struct {
}

func (o *RegenerateUserRobotTokenUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Unauthorized access
*/
type RegenerateUserRobotTokenForbidden struct {
}

func (o *RegenerateUserRobotTokenForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
Not found
*/
type RegenerateUserRobotTokenNotFound struct {
}

func (o *RegenerateUserRobotTokenNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
