package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type CreateOrgRobotReader struct {
	formats strfmt.Registry
}

func (o *CreateOrgRobotReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		var result CreateOrgRobotCreated
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result CreateOrgRobotBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("createOrgRobotBadRequest", &result, response.Code())

	case 401:
		var result CreateOrgRobotUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("createOrgRobotUnauthorized", &result, response.Code())

	case 403:
		var result CreateOrgRobotForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("createOrgRobotForbidden", &result, response.Code())

	case 404:
		var result CreateOrgRobotNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("createOrgRobotNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

/*CreateOrgRobotCreated

Succesfully created
*/
type CreateOrgRobotCreated struct {
	Payload *models.Robot
}

func (o *CreateOrgRobotCreated) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Robot)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*CreateOrgRobotBadRequest

Bad Request
*/
type CreateOrgRobotBadRequest struct {
	Payload *models.GeneralError
}

func (o *CreateOrgRobotBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*CreateOrgRobotUnauthorized

Session required
*/
type CreateOrgRobotUnauthorized struct {
}

func (o *CreateOrgRobotUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*CreateOrgRobotForbidden

Unauthorized access
*/
type CreateOrgRobotForbidden struct {
}

func (o *CreateOrgRobotForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*CreateOrgRobotNotFound

Not found
*/
type CreateOrgRobotNotFound struct {
}

func (o *CreateOrgRobotNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
