package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type GetOrgRobotsReader struct {
	formats strfmt.Registry
}

func (o *GetOrgRobotsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		var result GetOrgRobotsOK
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return &result, nil

	case 400:
		var result GetOrgRobotsBadRequest
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getOrgRobotsBadRequest", &result, response.Code())

	case 401:
		var result GetOrgRobotsUnauthorized
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getOrgRobotsUnauthorized", &result, response.Code())

	case 403:
		var result GetOrgRobotsForbidden
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getOrgRobotsForbidden", &result, response.Code())

	case 404:
		var result GetOrgRobotsNotFound
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, NewAPIError("getOrgRobotsNotFound", &result, response.Code())

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

/*GetOrgRobotsOK

Successful invocation
*/
type GetOrgRobotsOK struct {
}

func (o *GetOrgRobotsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetOrgRobotsBadRequest

Bad Request
*/
type GetOrgRobotsBadRequest struct {
	Payload *models.GeneralError
}

func (o *GetOrgRobotsBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*GetOrgRobotsUnauthorized

Session required
*/
type GetOrgRobotsUnauthorized struct {
}

func (o *GetOrgRobotsUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetOrgRobotsForbidden

Unauthorized access
*/
type GetOrgRobotsForbidden struct {
}

func (o *GetOrgRobotsForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetOrgRobotsNotFound

Not found
*/
type GetOrgRobotsNotFound struct {
}

func (o *GetOrgRobotsNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
