package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrgRobotParams creates a new GetOrgRobotParams object
// with the default values initialized.
func NewGetOrgRobotParams() *GetOrgRobotParams {
	var ()
	return &GetOrgRobotParams{}
}

/*GetOrgRobotParams contains all the parameters to send to the API endpoint
for the get org robot operation typically these are written to a http.Request
*/
type GetOrgRobotParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*RobotShortname
	  The short name for the robot, without any user or organization prefix

	*/
	RobotShortname string
}

// WithOrgname adds the orgname to the get org robot params
func (o *GetOrgRobotParams) WithOrgname(Orgname string) *GetOrgRobotParams {
	o.Orgname = Orgname
	return o
}

// WithRobotShortname adds the robotShortname to the get org robot params
func (o *GetOrgRobotParams) WithRobotShortname(RobotShortname string) *GetOrgRobotParams {
	o.RobotShortname = RobotShortname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgRobotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param robot_shortname
	if err := r.SetPathParam("robot_shortname", o.RobotShortname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
