package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserRobotPermissionsParams creates a new GetUserRobotPermissionsParams object
// with the default values initialized.
func NewGetUserRobotPermissionsParams() *GetUserRobotPermissionsParams {
	var ()
	return &GetUserRobotPermissionsParams{}
}

/*GetUserRobotPermissionsParams contains all the parameters to send to the API endpoint
for the get user robot permissions operation typically these are written to a http.Request
*/
type GetUserRobotPermissionsParams struct {

	/*RobotShortname
	  The short name for the robot, without any user or organization prefix

	*/
	RobotShortname string
}

// WithRobotShortname adds the robotShortname to the get user robot permissions params
func (o *GetUserRobotPermissionsParams) WithRobotShortname(RobotShortname string) *GetUserRobotPermissionsParams {
	o.RobotShortname = RobotShortname
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserRobotPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param robot_shortname
	if err := r.SetPathParam("robot_shortname", o.RobotShortname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
