package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetMatchingEntitiesParams creates a new GetMatchingEntitiesParams object
// with the default values initialized.
func NewGetMatchingEntitiesParams() *GetMatchingEntitiesParams {
	var ()
	return &GetMatchingEntitiesParams{}
}

/*GetMatchingEntitiesParams contains all the parameters to send to the API endpoint
for the get matching entities operation typically these are written to a http.Request
*/
type GetMatchingEntitiesParams struct {

	/*IncludeOrgs
	  Whether to include orgs names.

	*/
	IncludeOrgs *bool
	/*IncludeTeams
	  Whether to include team names.

	*/
	IncludeTeams *bool
	/*Namespace
	  Namespace to use when querying for org entities.

	*/
	Namespace *string
	/*Prefix*/
	Prefix string
}

// WithIncludeOrgs adds the includeOrgs to the get matching entities params
func (o *GetMatchingEntitiesParams) WithIncludeOrgs(includeOrgs *bool) *GetMatchingEntitiesParams {
	o.IncludeOrgs = includeOrgs
	return o
}

// WithIncludeTeams adds the includeTeams to the get matching entities params
func (o *GetMatchingEntitiesParams) WithIncludeTeams(includeTeams *bool) *GetMatchingEntitiesParams {
	o.IncludeTeams = includeTeams
	return o
}

// WithNamespace adds the namespace to the get matching entities params
func (o *GetMatchingEntitiesParams) WithNamespace(namespace *string) *GetMatchingEntitiesParams {
	o.Namespace = namespace
	return o
}

// WithPrefix adds the prefix to the get matching entities params
func (o *GetMatchingEntitiesParams) WithPrefix(prefix string) *GetMatchingEntitiesParams {
	o.Prefix = prefix
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetMatchingEntitiesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.IncludeOrgs != nil {

		// query param includeOrgs
		var qrIncludeOrgs bool
		if o.IncludeOrgs != nil {
			qrIncludeOrgs = *o.IncludeOrgs
		}
		qIncludeOrgs := swag.FormatBool(qrIncludeOrgs)
		if qIncludeOrgs != "" {
			if err := r.SetQueryParam("includeOrgs", qIncludeOrgs); err != nil {
				return err
			}
		}

	}

	if o.IncludeTeams != nil {

		// query param includeTeams
		var qrIncludeTeams bool
		if o.IncludeTeams != nil {
			qrIncludeTeams = *o.IncludeTeams
		}
		qIncludeTeams := swag.FormatBool(qrIncludeTeams)
		if qIncludeTeams != "" {
			if err := r.SetQueryParam("includeTeams", qIncludeTeams); err != nil {
				return err
			}
		}

	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string
		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {
			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}

	}

	// path param prefix
	if err := r.SetPathParam("prefix", o.Prefix); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
