package repositorynotification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetRepoNotificationParams creates a new GetRepoNotificationParams object
// with the default values initialized.
func NewGetRepoNotificationParams() *GetRepoNotificationParams {
	var ()
	return &GetRepoNotificationParams{}
}

/*GetRepoNotificationParams contains all the parameters to send to the API endpoint
for the get repo notification operation typically these are written to a http.Request
*/
type GetRepoNotificationParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*UUID
	  The UUID of the notification

	*/
	UUID string
}

// WithRepository adds the repository to the get repo notification params
func (o *GetRepoNotificationParams) WithRepository(repository string) *GetRepoNotificationParams {
	o.Repository = repository
	return o
}

// WithUUID adds the uuid to the get repo notification params
func (o *GetRepoNotificationParams) WithUUID(uuid string) *GetRepoNotificationParams {
	o.UUID = uuid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepoNotificationParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
