package repositorynotification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepoNotificationsParams creates a new ListRepoNotificationsParams object
// with the default values initialized.
func NewListRepoNotificationsParams() *ListRepoNotificationsParams {
	var ()
	return &ListRepoNotificationsParams{}
}

/*ListRepoNotificationsParams contains all the parameters to send to the API endpoint
for the list repo notifications operation typically these are written to a http.Request
*/
type ListRepoNotificationsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
}

// WithRepository adds the repository to the list repo notifications params
func (o *ListRepoNotificationsParams) WithRepository(Repository string) *ListRepoNotificationsParams {
	o.Repository = Repository
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoNotificationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
