package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new image API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for image API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*Get the information available for the specified image.
 */
func (a *Client) GetImage(params *GetImageParams, authInfo client.AuthInfoWriter) (*GetImageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetImageParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:          "getImage",
		Method:      "GET",
		PathPattern: "/api/v1/repository/{repository}/image/{image_id}",
		Schemes:     []string{"https"},
		Params:      params,
		Reader:      &GetImageReader{formats: a.formats},
		AuthInfo:    authInfo,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetImageOK), nil
}

/*Get the list of changes for the specified image.
 */
func (a *Client) GetImageChanges(params *GetImageChangesParams, authInfo client.AuthInfoWriter) (*GetImageChangesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetImageChangesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:          "getImageChanges",
		Method:      "GET",
		PathPattern: "/api/v1/repository/{repository}/image/{image_id}/changes",
		Schemes:     []string{"https"},
		Params:      params,
		Reader:      &GetImageChangesReader{formats: a.formats},
		AuthInfo:    authInfo,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetImageChangesOK), nil
}

/*List the images for the specified repository.
 */
func (a *Client) ListRepositoryImages(params *ListRepositoryImagesParams, authInfo client.AuthInfoWriter) (*ListRepositoryImagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListRepositoryImagesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:          "listRepositoryImages",
		Method:      "GET",
		PathPattern: "/api/v1/repository/{repository}/image/",
		Schemes:     []string{"https"},
		Params:      params,
		Reader:      &ListRepositoryImagesReader{formats: a.formats},
		AuthInfo:    authInfo,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListRepositoryImagesOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}

// NewAPIError creates a new API error
func NewAPIError(opName string, response interface{}, code int) APIError {
	return APIError{
		OperationName: opName,
		Response:      response,
		Code:          code,
	}
}

// APIError wraps an error model and captures the status code
type APIError struct {
	OperationName string
	Response      interface{}
	Code          int
}

func (a APIError) Error() string {
	return fmt.Sprintf("%s (status %d): %+v ", a.OperationName, a.Code, a.Response)
}
