package repotoken

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// DeleteTokenReader is a Reader for the DeleteToken structure.
type DeleteTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteTokenReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteTokenNoContent creates a DeleteTokenNoContent with default headers values
func NewDeleteTokenNoContent() *DeleteTokenNoContent {
	return &DeleteTokenNoContent{}
}

/*DeleteTokenNoContent handles this case with default header values.

Deleted
*/
type DeleteTokenNoContent struct {
}

func (o *DeleteTokenNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repository/{repository}/tokens/{code}][%d] deleteTokenNoContent ", 204)
}

func (o *DeleteTokenNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteTokenBadRequest creates a DeleteTokenBadRequest with default headers values
func NewDeleteTokenBadRequest() *DeleteTokenBadRequest {
	return &DeleteTokenBadRequest{}
}

/*DeleteTokenBadRequest handles this case with default header values.

Bad Request
*/
type DeleteTokenBadRequest struct {
	Payload *models.APIError
}

func (o *DeleteTokenBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repository/{repository}/tokens/{code}][%d] deleteTokenBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteTokenBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTokenUnauthorized creates a DeleteTokenUnauthorized with default headers values
func NewDeleteTokenUnauthorized() *DeleteTokenUnauthorized {
	return &DeleteTokenUnauthorized{}
}

/*DeleteTokenUnauthorized handles this case with default header values.

Session required
*/
type DeleteTokenUnauthorized struct {
	Payload *models.APIError
}

func (o *DeleteTokenUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repository/{repository}/tokens/{code}][%d] deleteTokenUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteTokenUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTokenForbidden creates a DeleteTokenForbidden with default headers values
func NewDeleteTokenForbidden() *DeleteTokenForbidden {
	return &DeleteTokenForbidden{}
}

/*DeleteTokenForbidden handles this case with default header values.

Unauthorized access
*/
type DeleteTokenForbidden struct {
	Payload *models.APIError
}

func (o *DeleteTokenForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repository/{repository}/tokens/{code}][%d] deleteTokenForbidden  %+v", 403, o.Payload)
}

func (o *DeleteTokenForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteTokenNotFound creates a DeleteTokenNotFound with default headers values
func NewDeleteTokenNotFound() *DeleteTokenNotFound {
	return &DeleteTokenNotFound{}
}

/*DeleteTokenNotFound handles this case with default header values.

Not found
*/
type DeleteTokenNotFound struct {
	Payload *models.APIError
}

func (o *DeleteTokenNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/repository/{repository}/tokens/{code}][%d] deleteTokenNotFound  %+v", 404, o.Payload)
}

func (o *DeleteTokenNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
