package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Avatar Avatar avatar

swagger:model Avatar
*/
type Avatar struct {

	/* Color color
	 */
	Color *string `json:"color,omitempty"`

	/* Hash hash
	 */
	Hash *string `json:"hash,omitempty"`

	/* Kind kind
	 */
	Kind *string `json:"kind,omitempty"`

	/* Name name
	 */
	Name *string `json:"name,omitempty"`
}

// Validate validates this avatar
func (m *Avatar) Validate(formats strfmt.Registry) error {
	return nil
}
