package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*TeamPermission Description of a team permission.

swagger:model TeamPermission
*/
type TeamPermission struct {

	/* Role to use for the team

	Required: true
	*/
	Role *string `json:"role"`
}

// Validate validates this team permission
func (m *TeamPermission) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var teamPermissionTypeRolePropEnum []interface{}

// prop value enum
func (m *TeamPermission) validateRoleEnum(path, location string, value string) error {
	if teamPermissionTypeRolePropEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["read","write","admin"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			teamPermissionTypeRolePropEnum = append(teamPermissionTypeRolePropEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, teamPermissionTypeRolePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TeamPermission) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role); err != nil {
		return err
	}

	return nil
}
