package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

// NewCreateStarParams creates a new CreateStarParams object
// with the default values initialized.
func NewCreateStarParams() *CreateStarParams {
	var ()
	return &CreateStarParams{}
}

/*CreateStarParams contains all the parameters to send to the API endpoint
for the create star operation typically these are written to a http.Request
*/
type CreateStarParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.NewStarredRepository
}

// WithBody adds the body to the create star params
func (o *CreateStarParams) WithBody(body *models.NewStarredRepository) *CreateStarParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateStarParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.NewStarredRepository)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
