package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/coreos/go-quay/models"
)

type DeleteStarReader struct {
	formats strfmt.Registry
}

func (o *DeleteStarReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteStarNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteStarBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteStarUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteStarForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteStarNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteStarNoContent creates a DeleteStarNoContent with default headers values
func NewDeleteStarNoContent() *DeleteStarNoContent {
	return &DeleteStarNoContent{}
}

/*DeleteStarNoContent

Deleted
*/
type DeleteStarNoContent struct {
}

func (o *DeleteStarNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/user/starred/{repository}][%d] deleteStarNoContent ", 204)
}

func (o *DeleteStarNoContent) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStarBadRequest creates a DeleteStarBadRequest with default headers values
func NewDeleteStarBadRequest() *DeleteStarBadRequest {
	return &DeleteStarBadRequest{}
}

/*DeleteStarBadRequest

Bad Request
*/
type DeleteStarBadRequest struct {
	Payload *models.GeneralError
}

func (o *DeleteStarBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/user/starred/{repository}][%d] deleteStarBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteStarBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteStarUnauthorized creates a DeleteStarUnauthorized with default headers values
func NewDeleteStarUnauthorized() *DeleteStarUnauthorized {
	return &DeleteStarUnauthorized{}
}

/*DeleteStarUnauthorized

Session required
*/
type DeleteStarUnauthorized struct {
}

func (o *DeleteStarUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/user/starred/{repository}][%d] deleteStarUnauthorized ", 401)
}

func (o *DeleteStarUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStarForbidden creates a DeleteStarForbidden with default headers values
func NewDeleteStarForbidden() *DeleteStarForbidden {
	return &DeleteStarForbidden{}
}

/*DeleteStarForbidden

Unauthorized access
*/
type DeleteStarForbidden struct {
}

func (o *DeleteStarForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/user/starred/{repository}][%d] deleteStarForbidden ", 403)
}

func (o *DeleteStarForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteStarNotFound creates a DeleteStarNotFound with default headers values
func NewDeleteStarNotFound() *DeleteStarNotFound {
	return &DeleteStarNotFound{}
}

/*DeleteStarNotFound

Not found
*/
type DeleteStarNotFound struct {
}

func (o *DeleteStarNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/user/starred/{repository}][%d] deleteStarNotFound ", 404)
}

func (o *DeleteStarNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
