package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserInformationParams creates a new GetUserInformationParams object
// with the default values initialized.
func NewGetUserInformationParams() *GetUserInformationParams {
	var ()
	return &GetUserInformationParams{}
}

/*GetUserInformationParams contains all the parameters to send to the API endpoint
for the get user information operation typically these are written to a http.Request
*/
type GetUserInformationParams struct {

	/*Username*/
	Username string
}

// WithUsername adds the username to the get user information params
func (o *GetUserInformationParams) WithUsername(Username string) *GetUserInformationParams {
	o.Username = Username
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserInformationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
